feat: adds cofc process flowchart & report form
CodeWithGroup/CodeWithGroup.github.io pull request #98
Opened 2021-07-03 14:26 UTC by daffodil11

2021-07-04 13:21 UTC, KeiranWDigital commented
Please could you swap the branch you are merging to to be "release"

2021-08-15 11:08 UTC, daffodil11 commented
The Code of Conduct Committee has had an opportunity to review the changes to the Code of Conduct and this PR is now ready for general review.

2021-08-27 17:32 UTC, KeiranWDigital requested changes
Just one slight suggestion on the markdown file.

Also, I think we should update the text at the bottom to say when it was last updated. 

Thanks for putting this together, looks really good!

2021-08-27 17:32 UTC, KeiranWDigital commented on code-of-conduct.md
> +If you wish to report something, please use [this form]({{site.url}}/code-of-conduct-report) to send a report directly to the Code of Conduct Committee.
I'd prefer this to be something like "please use the Code Of Conduct Report Form" as its more accessible to those who use screen readers

2021-08-31 20:32 UTC, daffodil11 commented on code-of-conduct.md
> +If you wish to report something, please use [this form]({{site.url}}/code-of-conduct-report) to send a report directly to the Code of Conduct Committee.
Very good point. Updated.

2021-08-31 20:34 UTC, KeiranWDigital commented
Happy with this, thanks :)

2021-08-31 20:35 UTC, KeiranWDigital approved these changes

2021-08-31 20:35 UTC, merged